In [3]:
import pandas as pd
import numpy as np

In [2]:
df=pd.read_csv("spam.csv")
df.head()

Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [4]:
df.Category.value_counts()

ham     4825
spam     747
Name: Category, dtype: int64

In [5]:
df['Spam']=df.Category.apply(lambda x: 1 if x=='spam' else 0)

In [6]:
df.head()

Category                                            Message  Spam
0      ham  Go until jurong point, crazy.. Available only ...     0
1      ham                      Ok lar... Joking wif u oni...     0
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...     1
3      ham  U dun say so early hor... U c already then say...     0
4      ham  Nah I don't think he goes to usf, he lives aro...     0

In [7]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(df.Message,df.Spam,test_size=0.2,random_state=56)

In [11]:
from sklearn.feature_extraction.text import CountVectorizer

In [12]:
v=CountVectorizer()
X_train_cv=v.fit_transform(X_train.values)

In [13]:
X_train_cv.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [20]:
v.get_feature_names_out()[2143]

'da'

In [14]:
v.vocabulary_

{'still': 6533,
 'attending': 1133,
 'da': 2143,
 'talks': 6753,
 'tap': 6760,
 'spile': 6431,
 'at': 1118,
 'seven': 6084,
 'is': 3769,
 'that': 6861,
 'pub': 5523,
 'on': 4973,
 'gas': 3089,
 'st': 6475,
 'off': 4930,
 'broad': 1520,
 'by': 1598,
 'canal': 1639,
 'ok': 4954,
 'wonder': 7641,
 'how': 3535,
 'you': 7771,
 'got': 3205,
 'online': 4983,
 'my': 4703,
 'love': 4248,
 'had': 3302,
 'gone': 3186,
 'to': 6984,
 'the': 6865,
 'net': 4782,
 'cafe': 1605,
 'did': 2296,
 'get': 3123,
 'your': 7776,
 'phone': 5227,
 'recharged': 5669,
 'were': 7518,
 'friends': 3009,
 'think': 6898,
 'of': 4928,
 'boytoy': 1478,
 'update': 7240,
 'face': 2736,
 'book': 1431,
 'status': 6509,
 'frequently': 3002,
 'does': 2378,
 'not': 4864,
 'operate': 4999,
 'after': 849,
 'lt': 4271,
 'gt': 3269,
 'or': 5013,
 'what': 7532,
 'important': 3646,
 'message': 4483,
 'this': 6906,
 'final': 2846,
 'contact': 1978,
 'attempt': 1129,
 'have': 3365,
 'messages': 4485,
 'waiting': 7414,
 'out': 5049,
 'o

In [16]:
X_train_np=X_train_cv.toarray()

In [18]:
X_train_np[0]

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [22]:
X_train_np[0].shape

(7812,)

In [19]:
np.where(X_train_np[0]!=0)

(array([1133, 2143, 6533, 6753], dtype=int64),)

In [23]:
from sklearn.naive_bayes import MultinomialNB

In [24]:
model=MultinomialNB()
model.fit(X_train_cv,y_train)

MultinomialNB()

In [25]:
X_test_cv=v.transform(X_test)

In [28]:
from sklearn.metrics import classification_report

In [29]:
y_pred=model.predict(X_test_cv)

In [30]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.99      1.00      0.99       959
           1       0.99      0.92      0.95       156

    accuracy                           0.99      1115
   macro avg       0.99      0.96      0.97      1115
weighted avg       0.99      0.99      0.99      1115



In [33]:
emails = [
    'Hey mohan, can we get together to watch footbal game tomorrow?',
    'Upto 20% discount on parking, exclusive offer just for you. Dont miss this reward!',
    'i have a exclusive credit card offer only for you',
    'lets play cricket together'
]
email_count=v.transform(emails)
model.predict(email_count)

array([0, 1, 1, 0], dtype=int64)